steps:
  # Step 1: Build Docker image
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-app-repo/gcp-cicd-portfolio-app:$SHORT_SHA
      - .

  # Step 2: Push Docker image to Artifact Registry
  - id: 'Push Image to Artifact Registry'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-app-repo/gcp-cicd-portfolio-app:$SHORT_SHA

  # Step 3: Deploy application to GKE using Cloud Deploy
  - id: 'Deploy to GKE Cluster'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - release-$SHORT_SHA
      - --delivery-pipeline=gcp-cicd-portfolio-pipeline
      - --region=asia-south1
      - --images=gcp-cicd-portfolio-app=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-app-repo/gcp-cicd-portfolio-app:$SHORT_SHA

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-app-repo/gcp-cicd-portfolio-app:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY